index:
    path: /api/v1/images/upload
    controller: App\Controller\ImageController::index
    methods: POST

images:
    path: /api/v1/images/
    controller: App\Controller\ImageController::getImagesList
    methods: GET

get_info_image:
    path: /api/v1/images/{filename}
    controller: App\Controller\ImageController::getImageInfo

get_image:
    path: /image/{origin}/{filename}
    controller: App\Controller\ImageController::getImage
    methods: GET
